application: call-for-design 
version: 1
runtime: php55
api_version: 1

handlers:
# Serve images as static resources
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts
- url: /root.php
  script: root.php 
  login: admin

- url: /install.php
  script: install.php

- url: /(.+\.php)$
  script: \1

- url: /stylesheets
  static_dir: stylesheets

- url: /lib/validator.min.js
  script: lib/validator.min.js

- url: /lib/bootstrap/
  static_dir: lib/bootstrap 

- url: /lib/jquery
  static_dir: lib/jquery

- url: /
  script: index.php
