application: testapp 
version: 1
runtime: php55
api_version: 1

handlers:
# Serve images as static resources
- url: /(.+\.(gif|png|jpg))$
  static_files: \1
  upload: .+\.(gif|png|jpg)$
  application_readable: true

# Serve php scripts
- url: /root.php
  script: root.php
  login: admin

- url: /(.(admin|login|regist|view|delete|vote|add).php)$
  script: (admin|login|regist|view|delete|vote|add).php

- url: /(.+\.css)$
  script: \1

- url: /lib/validator.min.js
  script: lib/validator.min.js

- url: /(lib/bootstrap/.+\)$
  script: "lib/boostrap/"\1

- url: /(lib/jquery/.\)$
  script: "lib/jquery/"\1

- url: /.*
  script: index.php
